export type AppAccentPalette =
  | "blue"
  | "purple"
  | "green"
  | "orange"
  | "yellow"
  | "red";

export type AppNeutralPalette = "gray";

export type AppPalette = AppNeutralPalette | AppAccentPalette;

export type SemanticColorTokenKey =
  | "app.bg.canvas"
  | "app.bg.surface"
  | "app.bg.surfaceMuted"
  | "app.bg.card"
  | "app.bg.cardHeader"
  | "app.bg.overlay"
  | "app.fg.default"
  | "app.fg.muted"
  | "app.fg.subtle"
  | "app.fg.link"
  | "app.fg.linkHover"
  | "app.fg.icon"
  | "app.fg.inverse"
  | "app.border.default"
  | "app.border.muted"
  | "app.border.strong"
  | "app.border.accent"
  | "app.status.info.bg"
  | "app.status.info.fg"
  | "app.status.success.bg"
  | "app.status.success.fg"
  | "app.status.warning.bg"
  | "app.status.warning.fg"
  | "app.status.danger.bg"
  | "app.status.danger.fg"
  | "app.status.neutral.bg"
  | "app.status.neutral.fg"
  | "app.prose.heading"
  | "app.prose.body"
  | "app.prose.subtle"
  | "app.prose.link"
  | "app.prose.linkHover"
  | "app.prose.codeBg"
  | "app.prose.preBg"
  | "app.prose.inlineCodeBg"
  | "app.prose.inlineCodeFg"
  | "app.prose.border"
  | "app.brand.linkedin.solid"
  | "app.brand.linkedin.soft"
  | "app.brand.linkedin.contrast"
  | "app.syntax.comment"
  | "app.syntax.keyword"
  | "app.syntax.string"
  | "app.syntax.number"
  | "app.syntax.function";